export const data = [
  {id: 1, empty: true, light: false},
  {id: 1, empty: true, light: false},
  {id: 1, empty: true, light: false},
  {id: 1, empty: true, light: false},
  {id: 1, empty: true, light: false},
  {id: 1, empty: true, light: false},
  {id: 1, empty: true, light: false},
  {id: 1, empty: true, light: false},
  {id: 1, empty: true, light: false},
  {id: 1, empty: true, light: false},
  {id: 1, empty: true, light: false},
  {id: 1, empty: true, light: false},
  {id: 1, empty: true, light: false},
  {id: 1, empty: true, light: false},
  {id: 1, empty: true, light: false},
  {id: 1, empty: true, light: false},
  {id: 1, empty: true, light: false},
  {id: 1, empty: true, light: false},
  {id: 1, empty: true, light: false},
  {id: 1, empty: true, light: false}, 
];
