export const data = [
  {id: 0, empty: true, light: false},
  {id: 0, empty: true, light: false},
  {id: 0, empty: true, light: false},
  {id: 0, empty: true, light: false},
  {id: 0, empty: true, light: false},
  {id: 0, empty: true, light: false},
  {id: 0, empty: true, light: false},
  {id: 0, empty: true, light: false},
  {id: 0, empty: true, light: false},
  {id: 0, empty: true, light: false},
  {id: 0, empty: true, light: false},
  {id: 0, empty: true, light: false},
  {id: 0, empty: true, light: false},
  {id: 0, empty: true, light: false},
  {id: 0, empty: true, light: false},
  {id: 0, empty: true, light: false},
  {id: 0, empty: true, light: false},
  {id: 0, empty: true, light: false},
  {id: 0, empty: true, light: false},
  {id: 0, empty: true, light: false}, 
];
